version: '3'
networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 182.17.0.0/16
          gateway: 182.17.0.1

services:
  das-database:
    image: slagga/das-database:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/das-database", "--config", "/app/config/config.yaml" ]
    ports:
      - "8118:8118"
    volumes:
      - $PWD/config/config.database.yaml:/app/config/config.yaml
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql-data:/var/lib/mysql
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
      # This allows ip ranges from 182.17.0.1 to 182.17.255.255 to connect to root
      MYSQL_ROOT_HOST: "182.17.%.%"
    networks:
      - mynetwork

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - $PWD/mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=smt
    networks:
      - mynetwork

  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  sub-account:
    image: slagga/sub-account:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/sub-account", "--config", "/app/config/config.yaml" ]
    ports:
      - "8125:8125"
      - "8126:8126"
    volumes:
      - $PWD/config/config.yaml:/app/config/config.yaml
    depends_on:
      - das-database
      - mongo
      - redis
    networks:
      - mynetwork