server:
  is_update: false
  net: 2 # 1 mainnet 2 testnet
  http_server_addr: ":8125"
  http_server_internal_addr: ":8126"
  parser_url: "http://127.0.0.1:8118/v1" # das-database
  server_address: ""
  server_private_key: ""
  smt_server: "http://10.143.1.180:10000"
  uni_pay_url: "http://127.0.0.1:9092"
  refund_switch: false
das:
  max_register_years: 20
  max_create_count: 100
  max_update_count: 100
  max_retry: 10
  auto_mint:
    support_payment_token:
      - "eth_eth"
      - "tron_trx"
      - "bsc_bnb"
      - "stripe_usd"
      - "tron_trc20_usdt"
      - "bsc_bep20_usdt"
      - "polygon_matic"
    background_colors:
      eth_eth: "#f0fdf4"
      tron_trx: "#eff6ff"
      bsc_bnb: "#fefce8"
    payment_min_price: 50
    service_fee_ratio: 0.1
  coupon:
    coupon_price: 0.99
    encryption_key: ""
    price_min: 0.99
    price_max: 500
  jwt_key: ""
origins:
  - ""
notify:
  lark_error_key: ""
  lark_create_sub_account_key: ""
  discord_create_sub_account_key: ""
chain:
  ckb_url: "https://testnet.ckb.dev/"
  index_url: "https://testnet.ckb.dev/indexer"
  current_block_number: 6900000 # mainnet 6900000, testnet2 4808730
  confirm_num: 4
  concurrency_num: 100
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "123456"
    db_name: "das_database"
    max_open_conn: 100
    max_idle_conn: 50
  parser_mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "123456"
    db_name: "das_database"
    max_open_conn: 100
    max_idle_conn: 50
cache:
  redis:
    addr: "127.0.0.1:6379" # 172.17.0.1: docker 182.17.0.1: docker-compose
    password: ""
    db_num: 0
unipay_address_map:
  "evm": ""
  "tron": ""